- name: set host name
  shell: hostname
  register: host_name


- name: set host facts
  set_fact:
    #host_name: "{{ ansible_facts['hostname'] }}"
    host_ip: "{{ inventory_hostname }}"
    host_name: "{{ host_name.stdout }}"

- name: test template
  template:
    src=hosts.j2
    dest=/etc/hosts
